## Numpy Library

NumPy, short for Numerical Python, serves as a foundational library in Python for numerical and scientific computing. 
It provides support for large, multi-dimensional arrays and matrices, along with an extensive collection of high-level mathematical functions to operate on these arrays efficiently.

what is an array?

An array is a data structure that stores a collection of elements of the same data type in contiguous memory locations. It allows you to organize and access multiple values using a single variable name and an index. Each element in the array has a specific position, starting from index 0, which is used to access or modify the element. 

In [4]:
## numpy library import

import numpy as np

In [6]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [8]:
type(arr)

numpy.ndarray

In [10]:
## 1D-array
arr

array([1, 2, 3, 4, 5])

In [12]:
arr.shape

(5,)

In [14]:
## multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [16]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
## 2d-array
## output attribute - (row,column)
arr.shape

(3, 5)

In [20]:
## convert the array shape
## previously it was (3,5) but now its (5,3)

arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [22]:
## new shape
arr.shape

(3, 5)

In [24]:
## its still a 2d-array
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

### Indexing

In [26]:
## accessing the array elements
arr=np.array([1,2,3,4,5,6,7,8,9])

In [29]:
arr[3]

4

In [31]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
## multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [54]:
## output attribute - (row,column)

arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [56]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [58]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [60]:
arr[1:,3]

array([5, 8])

In [64]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [66]:
arr[1,1:4]

array([3, 4, 5])

In [80]:
## in-built function
## giving indexing range  - lower/upper

## ARANGE

arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
## arange attribute - arange([start,] stop[, step,], dtype=None, *, like=None)

arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [86]:
## LINSPACE
## equally divide the points.
## np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0,)

np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [96]:
## COPY() FUNCTION AND BROADCASTING
## what is value type? and reference type?

arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr[3:] = 100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [100]:
arr1=arr

In [102]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [104]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [106]:
arr1=arr.copy()

In [108]:
## here it is creating another memory space to store arr1

print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [110]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [116]:
## some useful conditions in exploratory data analysis
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [118]:
## we have set the var as 2
val=2
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [120]:
arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [124]:
## to get the exact number instead of True/False
arr[arr<300]

array([1, 2, 3])

In [128]:
 ## craete arrays and reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [130]:
arr1 = np.arange(0,10).reshape(2,5)

In [132]:
arr2 = np.arange(0,10).reshape(2,5)

In [134]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [138]:
## ones() - np.ones(shape, dtype=None, order='C', *, like=None)

np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [140]:
np.ones((2,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [142]:
## random distribution

np.random.rand(3,3)

array([[0.70590131, 0.554893  , 0.82738149],
       [0.73083253, 0.62908702, 0.10390598],
       [0.89584177, 0.38480371, 0.31893071]])

In [146]:
## randn - Return a sample (or samples) from the "standard normal" distribution.

arr_ex = np.random.randn(4,4)
arr_ex

array([[ 1.08423529, -2.00887582,  1.27495986, -1.61858259],
       [-0.2578388 ,  0.17026353, -1.66229542,  0.75431243],
       [-0.19975528, -0.31771085,  1.70970917, -0.7472845 ],
       [ 0.3290236 ,  0.45946584, -0.86218251, -0.88141841]])

In [148]:
## randint
## 8 numbers between 0-100 in 4,2 shape

np.random.randint(0,100,8).reshape(4,2)

array([[75, 62],
       [81, 57],
       [55, 12],
       [22, 82]])

In [154]:
## random_shape - Return random floats in the half-open interval [0.0, 1.0).

np.random.random_sample((1,5))

array([[0.35074705, 0.91662997, 0.81582405, 0.17248147, 0.66275831]])